#---
# Spring Boot configuration
spring:
  profiles:
    active: development
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
    username: postgres 
    password: root
# JPA properties
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Cache
cache:
  classPathConfigLocation: ehcache.xml
  quizzer:
    name: quizzers
  push:
     name: push
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
# Server configuration
server:
  port: 8081
  sessionTimeout: 30
# Security configuration
security:
  user:
    name: Employee
    password: Employee