package com.devoteam.dls.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Test extends HorizontalLayout {
	protected Grid whosOnline;

	public Test() {
		Design.read(this);
	}
}
/*@Theme("Demo")
public class Test extends UI{
	
	private HorizontalSplitPanel mainLayout;
	@Override
	protected void init(VaadinRequest request) {
		mainLayout = new HorizontalSplitPanel();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100.0%");
		mainLayout.setHeight("100.0%");
		mainLayout.setMargin(false);
	}
	
}*/